configs:
  hasher:
    file: ./hasher/hasher.rb
  rng:
    file: ./rng/rng.py
  worker:
    file: ./worker/worker.py
  webui:
    file: ./webui/webui.js
services:
  hasher:
    command:
      - hasher.rb
    configs:
      - 
        mode: 0400
        source: hasher
        target: /hasher.rb
    deploy:
      placement:
        constraints:
          - node.role == worker
    entrypoint: ruby
    expose:
      - 8080
    image: academiaonline/dockercoins:2021-10-hasher
    networks:
      - hasher
  rng:
    command:
      - rng.py
    configs:
      - 
        mode: 0400
        source: rng
        target: /rng.py
    deploy:
      placement:
        constraints:
          - node.role == worker
    entrypoint: python
    expose:
      - 8080
    image: academiaonline/dockercoins:2021-10-rng
    networks:
      - rng
  worker:
    command:
      - worker.py
    configs:
      - 
        mode: 0400
        source: worker
        target: /worker.py
    deploy:
      placement:
        constraints:
          - node.role == worker
    entrypoint: python
    image: academiaonline/dockercoins:2021-10-worker
    networks:
      - hasher
      - redis
      - rng
version: '3.8'
